{
  pkgs,
  lib,
  inputs,
  ...
}: {
  nixpkgs.overlays = [
    (final: prev: {
      inherit
        (prev.lixPackageSets.latest)
        nixpkgs-review
        nix-eval-jobs
        nix-fast-build
        colmena
        ;
    })
    inputs.niri.overlays.niri
    inputs.nh.overlays.default
    inputs.ghostty.overlays.releasefast
    inputs.rio.overlays.default
    inputs.alejandra.overlays.default
    inputs.nixd.overlays.default
    # inputs.yazi.overlays.default
    inputs.quickshell.overlays.default
    inputs.helix.overlays.default
    inputs.nix-your-shell.overlays.default
  ];

  nix.package = pkgs.lixPackageSets.latest.lix;
  environment.systemPackages = with pkgs; [
    mindustry-wayland
    gearlever
    ibus
    kitty
    rio
    inputs.zen-test.packages.${stdenv.hostPlatform.system}.beta
    lsp-plugins
    zam-plugins
    calf
    mda_lv2
    aria2
    cacert
    inputs.nix-output-monitor.packages.${pkgs.stdenv.hostPlatform.system}.default
    nix-your-shell
    qutebrowser
    devenv
    xdg-ninja
    rich-cli
    yaziPlugins.vcs-files
    yaziPlugins.no-status
    yaziPlugins.rich-preview
    yaziPlugins.lazygit
    yaziPlugins.yatline
    yaziPlugins.yatline-githead
    yaziPlugins.full-border
    yaziPlugins.mount
    yaziPlugins.recycle-bin
    trash-cli
    yaziPlugins.sudo
    yaziPlugins.diff
    yaziPlugins.rsync
    qemu_kvm
    qemu
    libvirt
    virt-manager
    easyeffects
    taplo
    lazygit
    papirus-icon-theme
    starship
    onlyoffice-desktopeditors
    jq
    ollama
    opencode
    slurp
    quickshell
    satty
    grim
    xdg-desktop-portal-wlr
    xdg-desktop-portal-gtk
    util-linux
    tealdeer
    xorg.xrdb
    wlr-randr
    bluez
    fcitx5
    bibata-cursors
    gparted
    # floorp-bin
    appimage-run
    adw-gtk3
    ghostty
    niri-unstable
    xwayland-satellite-unstable
    localsend
    libadwaita
    unrar
    inteltool
    nushell
    go
    nirius
    vimPlugins.nvim-treesitter-parsers.nix
    vimPlugins.nvim-treesitter.builtGrammars.nix
    ouch
    tmux
    eza
    wl-clipboard
    (lib.hiPrio pkgs.wl-clipboard-rs)
    nh
    (yazi.override {
      _7zz = pkgs._7zz-rar;
    })
    nil
    cmake
    zed-editor
    wget
    firefox
    mesa-demos
    gtk4
    gtk3
    nautilus
    colloid-gtk-theme
    polkit_gnome
    btop
    gnome.gvfs
    nautilus-python
    zsh-powerlevel10k
    zsh-autosuggestions
    zsh-completions
    fzf
    zsh-syntax-highlighting
    ripgrep
    alejandra
    nixd
    wl-clip-persist
    podman
    greetd
    dbus
    dbus-broker
    nur.repos.Ev357.helium
    fastfetch
    lutris
    kdePackages.qt6ct
    kdePackages.qtmultimedia
    wineWowPackages.waylandFull
    libx11
    libxkbcommon
    libGL
    vulkan-loader
    vulkan-tools
    keepassxc
    kdlfmt
    adwaita-icon-theme
    material-symbols
    material-icons
    fd
    # inputs.nix-search-tv.packages.${pkgs.stdenv.hostPlatform.system}.default
    vscode-json-languageserver
    # (lib.hiPrio pkgs.uutils-coreutils-noprefix)
    upower
  ];
}
